name: PlayAgainAddon
version: '${project.version}'
main: me.zyypj.playagain.PlayAgainAddon
softdepend: [BedWars2023, BedWars1058, PlaceholderAPI]
commands:
  playagain:
    aliases: [jogarnovamente, pa]