name: PlayAgainAddon
version: '${project.version}'
main: me.zyypj.playagain.PlayAgainAddon
softdepend: [BedWars2023, BedWars1058, PlaceholderAPI, BedWarsProxy, BWProxy2023]
api-version: "1.13"
commands:
  playagain:
    aliases: [jogarnovamente, pa]